### ISSUE TITLE
'분' 단위가 60이 넘어가는 issue

### ISSUE THREAD

**Issue by sk000801** [kyw0716/Stopwatch-online#7]
🙌 @kyw0716 
![image](https://github.com/kyw0716/Stopwatch-online/assets/83707411/1c5b693a-5a6b-46d6-b93c-d55929eb352b)

스톱워치를 오랜만에 1시간이 넘게 사용하다가(문제가 어려웟삼),
1시간이 넘어갔는데 분 단위에 60이 그대로 찍혀있는 버그를 발견했습니다! 고쳐주세욧

**Comment by kyw0716** [comment]
넵 잠쉬만 기다려주세용 😍

**Comment by kyw0716** [comment]
수정 완료했습니다~~ 또 오류 발생하면 얘기해주세요!

수정한 커밋: 244987c0f0729083b09e615e00793896b5919d1f
